One_Help_ASP/Controllers/AssociationController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using One_Help_ASP.Data;
using One_Help_ASP.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
namespace One_Help_ASP.Controllers
{
    public class AssociationController : Controller
    {
        private readonly MyDbContext _context;
        public AssociationController(MyDbContext context)
        {
            _context = context;
        }


        public IActionResult Index()
        {
            try
            {
                if (HttpContext.Session.GetString("email") == null)
                {
                    return RedirectToAction("Login", "User");
                }

            }
            catch
            {
                return RedirectToAction("Login", "User");
            }


            var association = _context.Association.ToList();
            return View(association);
        }

        //Get-create
        public IActionResult Create()
        {
            return View();
        }

        //Post-create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Association association)
        {
            if (ModelState.IsValid)
            {
                _context.Association.Add(association);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(association);
        }


        //get-Delete


        public IActionResult Delete(int? id)
        {

            if (id == null || id == 0)
            {
                return NotFound();
            }
            var association = _context.Association.Find(id);
            if (association == null)
            {
                return NotFound();
            }
            return View(association);

        }
        //Post-Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var association = _context.Association.Find(id);
            if (association == null)
            {
                return NotFound();
            }

            _context.Association.Remove(association);
            _context.SaveChanges();
            return RedirectToAction("Index");

        }
        //get update
        public IActionResult Update(int? id)
        {

            if (id == null || id == 0)
            {
                return NotFound();
            }
            var association = _context.Association.Find(id);
            if (association == null)
            {
                return NotFound();
            }
            return View(association);

        }

        //Post-Update
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(Association association)
        {
            if (ModelState.IsValid)
            {
                _context.Association.Update(association);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(association);
        }

        //get detail
        public IActionResult Detail(int? id)
        {

            if (id == null || id == 0)
            {
                return NotFound();
            }
            var association = _context.Association.Find(id);
            if (association == null)
            {
                return NotFound();
            }
            return View(association);

        }
    }
}

One_Help_ASP/Controllers/BenevoleController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using One_Help_ASP.Data;
using One_Help_ASP.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace One_Help_ASP.Controllers
{
    public class BenevoleController : Controller
    {
        private readonly MyDbContext _context;
        public BenevoleController(MyDbContext context)
        {
            _context = context;
        }


        public IActionResult Index()
        {
            try
            {
                if (HttpContext.Session.GetString("email") == null)
                {
                    return RedirectToAction("Login", "User");
                }

            }
            catch
            {
                return RedirectToAction("Login", "User");
            }
            var benevole = _context.Benevole.ToList();
            return View(benevole);
        }

       //Get-create
        public IActionResult Create()
        {
            return View();
        }

        //Post-create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Benevole benevole)
        {
            if (ModelState.IsValid)
            {
                _context.Benevole.Add(benevole);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(benevole);
        }


        //get-Delete
       
      
        public IActionResult Delete(int? id)
        {
           
            if (id == null || id==0)
            {
                return NotFound();
            }
            var benevole = _context.Benevole.Find(id);
            if (benevole == null)
            {
                return NotFound();
            }
            return View(benevole);

        }
        //Post-Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var benevole = _context.Benevole.Find(id);
            if(benevole== null)
            {
                return NotFound();
            }
              
                _context.Benevole.Remove(benevole);
                _context.SaveChanges();
                return RedirectToAction("Index");
           
        }
        //get update
        public IActionResult Update(int? id)
        {

            if (id == null || id == 0)
            {
                return NotFound();
            }
            var benevole = _context.Benevole.Find(id);
            if (benevole == null)
            {
                return NotFound();
            }
            return View(benevole);

        }

        //Post-Update
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(Benevole benevole)
        {
            if (ModelState.IsValid)
            {
                _context.Benevole.Update(benevole);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(benevole);
        }

        //get detail
        public IActionResult Detail(int? id)
        {

            if (id == null || id == 0)
            {
                return NotFound();
            }
            var benevole = _context.Benevole.Find(id);
            if (benevole == null)
            {
                return NotFound();
            }
            return View(benevole);

        }

    }
}

One_Help_ASP/Controllers/UserController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Session;
using One_Help_ASP.Data;
using One_Help_ASP.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Xamarin.Essentials;

namespace One_Help_ASP.Controllers
{
    public class UserController : Controller
    {
        private readonly MyDbContext _context;

        public UserController(MyDbContext context)
        {
            _context = context;
        }
        //get name
        public IActionResult Index()
        {
            string userName = HttpContext.User.Identity.Name;
            return View(userName);
        }

        //get login
        public IActionResult Login()
        {
            return View();
        }

        //Post login
        [HttpPost]
        public IActionResult Login(User user)
        {
            var usr = _context.User.Where(x=> x.Email==user.Email && x.Password==user.Password );
            if (usr.Count() != 0)
            {
                HttpContext.Session.SetString("email", user.Email);
                //HttpContext.Session.SetString("statu", user.Statu);

               
                return RedirectToAction("Index", "Home");
               
            }
            else
            {
                TempData["msg"] = "Email/password  incorrect";
            }
            return View();

        }



        public IActionResult Logout()
        {  
            HttpContext.Session.Clear();
            return View("Login");
        }
    }
}

One_Help_ASP/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - One_Help_ASP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/lib/logo.png"/></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-end" >

                    @{
                        try
                        {


                            if (Context.Session.GetString("email") != null)
                            {
                                        <ul class="navbar-nav flex-grow-2">
                                            <li></li> <li></li> <li></li>
                                            <li class="nav-item">
                                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index" style=" font-size: 19px; font-weight:bold;">Accueil</a>
                                            </li>
                                            <li class="nav-item">
                                                <a class="nav-link text-dark" asp-area="" asp-controller="Benevole" asp-action="Index" style=" font-size: 19px; font-weight: bold;">Les Bénévoles</a>
                                            </li>
                                           
                                            <li class="nav-item">
                                                <a class="nav-link text-dark" asp-area="" asp-controller="Association" asp-action="Index" style=" font-size: 19px; font-weight: bold;">Les Associations</a>
                                            </li>
                                           
                                             <li class="nav-item">
                                                <a class="nav-link text-dark" style=" border: 1px solid red; border-radius: 5px; font-size: 11px; margin-top: 7px; font-weight: bold; " asp-area="" asp-controller="User" asp-action="Logout">Déconnexion</a>
                                            </li>
                                        </ul>
                            }
                        }
                        catch
                        {

                        }
                    }

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container" style="display:flex;justify-content: center;">
            &copy; 2022 - One_Help_ASP - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>